version: '3'
services:
 db:
  image: postgres
  volumes:
   - ./tmp/db:/var/lib/postgresql/data
 web:
  build:
   context: .
  command: bash -c "bundle exec puma -C config/puma.rb"
  volumes:
   - .:/careerWalk
  ports:
   - "3000:3000"
  depends_on:
   - db
 smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
 server:
  build:
   context: ./nginx
  volumes:
   - ./nginx/default.template:/etc/nginx/conf.d/default.conf
   - ./nginx/log.txt:/etc/nginx/log.txt
  ports:
   - "80:80"
  depends_on:
   - web
