version: '3'
services:
 db:
  image: postgres
  volumes:
   - ./tmp/db:/var/lib/postgresql/data
 web:
  build:
   context: .
  command: bash -c "bundle exec puma -C config/puma.rb"
  volumes:
   - .:/careerWalk
  ports:
   - "3000:3000"
  depends_on:
   - db
 server:
  build:
   context: ./nginx
  volumes:
   - ./nginx/default.template:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  depends_on:
   - web
